ekf_filter_node:
  ros__parameters:
    odom0: /odom_with_cov
    odom0_config: [true, true, false, false, false, true, false, false, false, false, false, false]
    odom_frame: odom
    base_link_frame: chassis
    world_frame: odom
    frequency: 10.0
    two_d_mode: true
    publish_tf: true
    disabled_at_startup: false
